# Generated by Django 3.2.3 on 2021-05-30 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testscore',
            old_name='candidate',
            new_name='candidate_name',
        ),
    ]
